# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ front-end-ejs ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: ls -a && pwd
    - name: SCP Upload
      # You may pin to the exact commit or the version.
      # uses: betanzos/scp-upload@4afbc824f4b0940d2b1ae862590033424385e3ab
      uses: betanzos/scp-upload@v1
      with:
        # Source local file path
        source: /home/runner/work/consuming-api-yt/consuming-api-yt
        # Remote host
        host: 207.246.115.236
        # Remote host SSH port
        port: 22
        # Remote host username
        username: root
        # SSH private key
        key: oK?48BNft7zQEJSb
        # Remote directory to copy the file
        remote_dir: /root/yt
