# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ front-end-ejs ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: ls -a && pwd
    - name: deploy-via-scp
      # You may pin to the exact commit or the version.
      # uses: horochx/deploy-via-scp@bf9a636d9a475a714e375ba1cc455d1c5c861aef
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        # Local file path
        local: /home/runner/work/consuming-api-yt/consuming-api-yt
        # Remote file path
        remote: /root/yt
        # Remote server address
        host: 207.246.115.236
        # Remote server port
        port: 22
        # Remote server user
        user: root
        # Remote server private key
        key: oK?48BNft7zQEJSb

